### PR TITLE
add copy flag to TCP writes

### PR DESCRIPTION
**Pull request by bertmelis**
0x03: ASYNC_WRITE_FLAG_COPY + ASYNC_WRITE_FLAG_MORE
0x01: ASYNC_WRITE_FLAG_COPY

### CODE REVIEW

**Review by proddy — COMMENTED** [review]
I thought the copy flag was 0x01 (ASYNC_WRITE_FLAG_COPY) not 0x03?

**Comment by proddy** [comment]
Also best to push these changes into a new dev branch, no?

**Comment by proddy** [comment]
> I thought the copy flag was 0x01 (ASYNC_WRITE_FLAG_COPY) not 0x03?

oops, just saw your comment above. sorry, ignore my stupidity

**Comment by proddy** [comment]
> 0x03: ASYNC_WRITE_FLAG_COPY + ASYNC_WRITE_FLAG_MORE
> 0x01: ASYNC_WRITE_FLAG_COPY

Also worth adding the advantage of making this change in the issue, explaining what it will improve. Does it just fill up the full LWIP buffer each time so less fragmented memory?

**Comment by bertmelis** [comment]
On a second thought, I might do it otherwise.

What If I create a TCP buffer (ringbuffer, underlying char array) with the size of the TCP MSS. It combines the solution of the ESPAsyncTCPBuffer and the dangling pointer. Because I'd create the buffer on object creation, no heap fragmentation will occur because of the buffer. The COPY flag as now in this PR does cause extra fragmentation.

ESPAsyncTCPBuffer could be used but it creates an extra 100 bytes incoming buffer which is not needed and it is not available on AsyncTCP for ESP32.

**Comment by proddy** [comment]
sounds like something to explore. I'm not an expert in this though, its too low level for me. What was pangolin's approach to this?

**Comment by bertmelis** [comment]
Pangolin keeps all message data in a packet-objects and uses a queue of pointers-to-objects. By doing that, you can implement retries etc for QoS > 0.

A TCP buffer is nothing more then an ringbuffer that holds the data:
when you write to asynctcp, you instead write to the buffer
upon send, you pass the head pointer of the buffer to the tcp lib (and take care of "rollover")
when an ack comes in, you move the head and make room in the buffer.

--> no dangling pointers, no heap fragmentation.

Size of the ringbuffer is to be freely chosen, but I'd take MSS. More then a few MQTT messages will fit in the buffer while memory usage is not too big. And when reaching MSS, it has to be passed to TCP anyway.

**Comment by proddy** [comment]
ok, that makes a lot of sense and guarantees transmission. Regarding MSS is this dependent on the lwip? I remember on the ESP8266 with lwip2 (-DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH) it's pretty high at 2090 bytes.

If you're implementing a ring buffer from within an interrupt a nice piece of code is https://github.com/nomis/EvohomeWirelessFW/blob/master/lib/InterruptSafeBuffer/InterruptSafeBuffer.h (by Simon Arlott)

**Comment by kleini** [comment]
Please make the size of this ringbuffer configurable. My Homie devices have so much properties, which they want to publish during startup, that I need a buffer to cover that amount of data to be sent: https://github.com/kleini/async-mqtt-client/commit/f1b42054815ad82fed4519bce7febb7f1601560f

**Comment by proddy** [comment]
@bertmelis if you want some help with setting up a branch and project let me know.

**Comment by bertmelis** [comment]
Closing this and redo in separate branch.

**Comment by luebbe** [comment]
Thanks @bertmelis. I wanted to ask you, if this PR should still be kept open.

**Comment by bertmelis** [comment]
Hmmm, I don't know how to branch... Off course, I can branch in my fork. But not upstream.

**Pull request closed without merging**
