### PR TITLE
esp32-fix-sending-malformed-packets

### PR DESCRIPTION
**Pull request by 9a4gl**
ESP32 has two CPU cores, it may happen that application sends publish on first CPU core, while at the same time on second CPU core publish is received and library automatically send on second CPU core ack. This ACK may send to (asynctcp) _client chunk of data in between chunks of publish sent on first CPU core.

This issue depends on traffic, with more exchanged publish messages there is higher chance to reproduce it. Also, with QOS>0 it is easier to reproduce as there are more ACKs.

### CODE REVIEW

**Comment by bertmelis** [comment]
I don't see how this PR would solve the **underlying** problem. All it does is create an intermediate buffer and copy this buffer to AsyncTCP.

**Comment by 9a4gl** [comment]
> I don't see how this PR would solve the **underlying** problem. All it does is create an intermediate buffer and copy this buffer to AsyncTCP.

Read my first comment above for this PR. ESP32 has two cores, if one core is sending ACK and other core is sending PUBLISH, those sending must be atomic operation for AsyncTCP client. Before my change each method called _client.add() multiple times to send single MQTT packets, if you do that in parallel from multiple cores you get mixed content. Hope it is clear now.

**Comment by 9a4gl** [comment]
Maybe the fix is not ideal, it would be much better to use mutex due to checking available space. It still may happen available space decrease and you send partial packet, but that is much less likely. Will give a try when I get some spare time.

**Comment by 9a4gl** [comment]
Created new PR that uses mutex, it works fine for few hours already. https://github.com/marvinroger/async-mqtt-client/pull/139

**Pull request closed without merging**
