### PR TITLE
ESP32 Support

### PR DESCRIPTION
**Pull request by timpur**

### CODE REVIEW

**Comment by marvinroger** [comment]
Perfect, thanks!

**Comment by marvinroger** [comment]
Hi @ivankravets,

As seen in https://github.com/me-no-dev/ESPAsyncWebServer/issues/223, two months later, is it still required to have two separate library.json, one for ESP8266 and the other for ESP32?

If we do need to have two separate manifests, I also have another problem: `platformio lib -g install file://.` does not pick up the manifests as they are not called `library.json`. Is there a way to specifiy a custom manifest file name?

Thanks! 👍

**Comment by ivankravets** [comment]
Hi @marvinroger ,

It was a temporary solution. See https://github.com/me-no-dev/ESPAsyncWebServer/pull/292

Please also use the same manifest for multiple dev/platforms with the latest PIO Core 3.5.0b6.

The final release of PIO Core 3.5.0 is planned for the next week.

**Comment by marvinroger** [comment]
@timpur do you have any idea about why it fails for ESP32: https://travis-ci.org/marvinroger/async-mqtt-client/jobs/308880480 ?

**Comment by ivankravets** [comment]
This is our bug with tool chain. We fixed it yesterday. Please clean cache and restart job.

**Comment by marvinroger** [comment]
@ivankravets it feels wrong to clear the cache everytime. I am not saying it is cumbersome, but why isn't there some hash system to determine whether there's a newer version?

**Comment by marvinroger** [comment]
It passes! Thanks a lot. 😄

**Comment by ivankravets** [comment]
There were 2 problems:

* You depend on old version of `ESPAsyncTCP` which does not have proper information in manifest (I fixed it manually on PIO side)
* ESP32 for Arduino has not been released yet. So, we still use development branch and sync it time to time with our stable dev/platform release. It seems that we have more users for ESP32+Arduino Core then just plain Arduino IDE for ESP32 users. As result, after the next release 1 day ago we received bug report with toolchain which was reported to ESP team. We fixed it together in a few hours. So, now all people should be happy :)

P.S: CI caching is good if you have multiple examples which use the same toolchain. In your case, you have the only 2 examples of different dev/platforms. You can comment these lines https://github.com/marvinroger/async-mqtt-client/blob/master/.travis.yml#L5:L7

**Pull request merged**
