### PR TITLE
Update a list with compatible platforms for @platformio

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by marvinroger** [comment]
@ivankravets any idea about what's wrong with [this build](https://travis-ci.org/marvinroger/async-mqtt-client/builds/308647187)? The ESP8266 example fails because of `Error: Could not find ESPAsyncTCP dependency for AsyncMqttClient library`, and the ESP32 examples fails because it tries to build ESPAsyncTCP which should only be used on ESP8266.

**Comment by ivankravets** [comment]
Could you remove TravisCI cache and restart a job?

- https://docs.travis-ci.com/user/caching/#Clearing-Caches

**Comment by marvinroger** [comment]
Done: https://travis-ci.org/marvinroger/async-mqtt-client/builds/308658238
The second issue is gone, now, the only problem is the dependency not found.

2017-11-28 23:38 GMT+01:00 Ivan Kravets <notifications@github.com>:

**Comment by ivankravets** [comment]
@marvinroger please do the same which you do with Homie. `pio lib -g install file://.` to ask PlatformIO install all dependencies from a library.

**Comment by marvinroger** [comment]
Done: https://travis-ci.org/marvinroger/async-mqtt-client/builds/308880476
Deps are installed, but it cannot find the libs at compile-time (look at the ESP8266 job)

**Comment by marvinroger** [comment]
And the cache is cleaned

**Comment by ivankravets** [comment]
Thanks! Fixed in https://github.com/platformio/platformio-core/commit/3c6bd9824e50394b6f2cce73f1b85184a9d591bc

Please clean cache and restart JOB.

P.S: The problem was with the old version of a library on which you depend. It uses old platform name `espressif`. I added support for this case.

**Comment by marvinroger** [comment]
Perfect! Fixed for ESP8266.
Now, I don't understand why the ESP32 example tries to build `ESPAsyncTCP.cpp`, which should only be built on the ESP8266 example, given there's a:

```c++
#ifdef ESP32
#include <AsyncTCP.h>
#elif defined(ESP8266)
#include <ESPAsyncTCP.h>
#else
#error Platform not supported
#endif
```

**Comment by ivankravets** [comment]
Ok, yet another fix https://github.com/platformio/platformio-core/commit/f922fac9d9ae6422548938c0e30192de1891eef8

So, it makes sense to replace `espressif` only by `espressif8266` because that was the previous name.

Please restart JOB.

**Comment by marvinroger** [comment]
Still not solved: https://travis-ci.org/marvinroger/async-mqtt-client/builds/308880476

**Comment by ivankravets** [comment]
I manually fixed manifests in old releases of ESPAsyncTCP. Could you try to clean up cache and restart a job?

**Pull request merged**
