### PR TITLE
Fix reconnect tyming

### PR DESCRIPTION
**Pull request by hotchpotch**
Hi.

I fixed example file because can't work ```mqttClient.connect()``` in disconnect callback.
maybe It works in main thread.

### CODE REVIEW

**Comment by marvinroger** [comment]
I'll let this on hold until I'm back from vacations, as `connect()` in the `disconnect()` callback *should* work. I'll take a look at everything then. Thanks for the contribution!

**Comment by eos1d3** [comment]
I do not think it can work. I did similar thing last month without success.  These include:

1. force a disconnection and a re-connection, it never connect again.
2. add a flag in disconnect call back and reconnect in main, it never connect too

And the worst thing is, the library sometimes never detects it is disconnected.

**Comment by marvinroger** [comment]
Thanks for the feedback.

**Comment by NeilSpp** [comment]
I also tested this way, is no working.
heartbeat time is 60s.
Undetectable get heartbeat response three times, force a disconnection and a re-connection, it never connect.

**Comment by me-no-dev** [comment]
referencing [this](https://github.com/marvinroger/async-mqtt-client/issues/18) issue as the reason for failed reconnects. Problem is on ESPAsyncTCP connect to dns hostname from async callback

**Comment by marvinroger** [comment]
Fixed in the latest revision of ESPAsyncTCP.

**Comment by hotchpotch** [comment]
@marvinroger 
Thanks for fixed it!

**Comment by marvinroger** [comment]
I did not do anything actually, all credits go to @me-no-dev

**Pull request closed without merging**
