### PR TITLE
Fixed ClientId for ESP32 + Disconnect Event

### PR DESCRIPTION
**Pull request by timpur**
Fixed clientId for ESP32 #90
Fix confusing disconnect event #83

### CODE REVIEW

**Comment by timpur** [comment]
Sorry @Adam5Wu and @vanvuongngo, i decided to take your tickets and include them in my branch, so i could test a tweek them. Please review my implementation of your bits.

**Comment by bertmelis** [comment]
Chip ID on esp8266 is **not** the MAC address. So maybe also change esp8266's implementation and use the MAC address for both.

So for esp8266 maybe something like this:
```C++
byte mac[6];
WiFi.macAddress(mac);
sprintf(_generatedClientId, "esp8266-%02x%02x%02x%02x%02x%02x", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
```
(I don't know why, but it prints all zeros?)

**Comment by timpur** [comment]
Is there any requirement for it to be a mac? Just so happens the chip ID on the esp32 is a mac...

**Comment by bertmelis** [comment]
That's not a requirement. But it is just very likely to be unique.

**Comment by timpur** [comment]
So is the chip id ?

**Comment by justoke** [comment]
Any chance the owner can give these oustanding pull requests some love? The ESP32 examples pretty much are not usable without these changes.

**Comment by DaleMitchell** [comment]
@timpur ?

**Comment by DaleMitchell** [comment]
@timpur @bertmelis Since MQTT is related to networking, I think it makes a lot more sense to use the MAC address for the client ID. But regardless, CHIP_ID is not unique. Espressif claims that the MAC address is unique. Source: https://bbs.espressif.com/viewtopic.php?t=1303#p4343

> by Espressif_Kelly
> CHIP_ID can not be used to uniquely indicate of ESP8266EX, because the chip_id of chips for the same batch is same.
> 
> You can use MAC address as the identifier. MAC address is pre-burned in the chip by efuse before delivery and MAC address of each chip are different.

**Comment by rljonesau** [comment]
The %06llx fix is SO GOOD and tidy - why is it not in master?
Just spent 2 days sorting this out with a remote customer :-(

**Comment by jeroenst** [comment]
Shouldn't it be %08llx?

**Comment by marvinroger** [comment]
Hi!
https://github.com/marvinroger/async-mqtt-client/pull/165 already fixed both these issues I think, and this is now in `master`. Can anybody confirm this?

**Pull request closed without merging**
