### PR TITLE
WIP: bugfixes and improvements

### PR DESCRIPTION
**Pull request by bertmelis**
**This is WIP**

Opened this PR in favour of https://github.com/marvinroger/async-mqtt-client/pull/211.

fixes:
- dangling pointers outgoing messages
- sending messages larger than TCP buffer
- half-open connections on multiple "connect"-calls
- disconnect when broker is lost

to do *(not limitative)*:
- sending QoS 2
- receiving QoS 2
- retry mechanism
- persist session accross connect/disconnect
- cleanup (lots of!)
- harmonize packet classes

### CODE REVIEW

**Comment by bertmelis** [comment]
next:
- free heap guard when creating packets
- persisting session (spec "3.1.2.4 Clean Session")
- sending qos 2
- retry mechanism --> question: how many tries, how much time between tries (depending on keepalive?)

anything else?
any remarks?

**Comment by proddy** [comment]
you've been busy, nice! I'll review

**Comment by bertmelis** [comment]
> you've been busy, nice! I'll review

Mind: I didn't do anything on the "packet encoding"

**Comment by bertmelis** [comment]
somethings fishy on ESP32... `InstrFetchProhibited`

**Comment by bertmelis** [comment]
> somethings fishy on ESP32... `InstrFetchProhibited`

OK, disabled debug logging and now it runs OK. I guess the abundance of logging statements makes the ESP crash.

**Comment by bertmelis** [comment]
Tried to implement session data saving across reconnects. I'm not sure if it works though. And I'm also not fully understanding the spec.

fixed:
- session data saving
- moved mutex macro to Helpers.hpp
- added logging (compile time selection)

new fatal error --> cleanup on ESP8266 results in crash (LoadStoreAlignment error)

**Comment by bertmelis** [comment]
- fixed sending QoS1 (package was deleted on ack but _sent counter wasn't reset)

Next:
- sending QoS 2
- receiving QoS1 (should work already, review/optimise only)
- receiving QoS2 (haven't used this yet)

Question: how to implement a retry mechanism for qos>0 messages? I'm in doubt here if we actually need this. If a message doesn't get though, the keepalive will disconnect and (when not configured as clean session) the message will automatically be resent upon the next connection. So unless you set the keepalive to a high value, there's no point in retrying.
Any ideas?

**Comment by bertmelis** [comment]
Question: should I already merge into the develop branch? It is easier for people to test, and mark improvements themselves.

**Comment by proddy** [comment]
I haven't had a chance to look at your new features yet (sorry, I did say I would review). I build a QOS1/2 retry into my implementation a while ago and its hard to do and not very reliable so I wouldn't bother.

Question: how are you testing this implementation? Did you build a test framework or unit tests that can be automated. If not, I could help there

**Comment by Pablo2048** [comment]
I'm testing this (actually bertmelis:develop branch) right now - I've just replaced original library with the new one in my application where I'm using my MQTTVPN. Unfortunately it crashes after approx. 30 seconds of runtime, so I have to extract the whole VPN thing to the hardware module, where I have access to the serial port for debugging...

**Comment by bertmelis** [comment]
I'm testing with a sketch that does some publishing (lot's of small, a few large), subscribe, unsubscribe en disconnect.

All based on the example.

Unit tests would be handy. I once set up a raspberry pi with platformio that ran tests remotely.

I wonder why your mqttvpn crashes. I suppose you use TLS? I haven't tested that but apart from establishing the connection, there's no real difference in usage of the TCP api's.

Anyway
- yes, implementation of tests is useful
- I guess I can merge into develop (isn't that why the branch exists...)
- Very interested in crash reports.

**Comment by Pablo2048** [comment]
> I wonder why your mqttvpn crashes. I suppose you use TLS? I haven't tested that but apart from establishing the connection, there's no real difference in usage of the TCP api's.

I don't use TLS right now actually. I've create just simple project for MQTTVPN testing and no more crashes so far (it behave way better actually with the develop version, because I see the multicast packets flowing through the VPN) so I have to investigate further where the problem is....

**Comment by bertmelis** [comment]
Sending messages using QOS 2 should work now.

Next:
- manage DUP flags in case of retry
- receiving qos 1
- receiving qos 2

**Comment by proddy** [comment]
@bertmelis great! can you merge the PR into `develop` so we can test. I don't think anyone else is using that branch so it's safe for experimenting.

**Comment by bertmelis** [comment]
Will merge tomorrow, after fixing the dup flag and merge conflicts. (shut off my computer)

I'll start a new PR for the receipt of messages.

**Comment by bertmelis** [comment]
merged (added DUP flag setting in separate PR, forgot about it).

I'll make a new PR for incoming message handling but from the first look I don't think I will have to do much updating.

**Pull request merged**
