### PR TITLE
v0.9.0

### PR DESCRIPTION
**Pull request by bertmelis**

### CODE REVIEW

**Comment by bertmelis** [comment]
Squash or not? Although there are some spurious commits, imo there are too many commits to squash them all together. On the other hand, commit history is also in the develop branch.

**Comment by proddy** [comment]
go for it!

**Comment by Pablo2048** [comment]
I did some quick tests on ESP8266 with the newest develop branch (uptime 6 hours so far) - for me it's green light...

**Comment by proddy** [comment]
I've been running on the ESP32 for ~20hrs...not a glitch

**Comment by luebbe** [comment]
I switched one of my devices to the develop branch (had it on a few test projects so far) and it's been working fine for a day and a half now. 
Green light from me for the functionality. I didn't review the code in detail, but the few snippets I looked at during the "making of" all looked plausible to me.

**Review by luebbe — APPROVED** [review]

**Comment by bertmelis** [comment]
Squash?

**Comment by luebbe** [comment]
I think squash is fine in this case. Looks tidier on main and every single commit is still preserved on develop

**Pull request merged**
